export { default as HomePage } from './HomePage';
export { default as CategoryPage } from './CategoryPage';
export { default as DetailPage } from './DetailPage';
export { default as MyCartPage } from './MyCartPage';
export { default as MyHistoryPage } from './MyHistoryPage';
export { default as MyJjimPage } from './MyJjimPage';
export { default as MyPage } from './MyPage';
export { default as MyProfilePage } from './MyProfilePage';
export { default as PopularPage } from './PopularPage';
