const mockUserList = {
  data: [
    {
      id: 1,
      title: '[비블리] 2만원대 무선 미니 무선 고데기',
      category: '뷰티',
      company: '(주)명성',
      percent: 123213,
      amount: 112313,
      spon: 1123,
      dueDate: 19,
      isJjimed: true,
      isSponsored: true,
      jim_date: new Date(2020, 10, 10, 11, 1),
      img: '',
    },
    {
      id: 2,
      title: '[LG] 선빼고 다드려요! 100만원대 노트북',
      category: '컴퓨터',
      company: '(주)LG',
      percent: 50,
      amount: 2131232,
      spon: 21212,
      dueDate: 23,
      isJjimed: true,
      isSponsored: true,
      jim_date: new Date(2020, 10, 19, 11, 1),
      img: '',
    },
    {
      id: 3,
      title: '[특가] 선빼고 다드려요! 2만원대 손난로',
      category: '가전',
      company: '(주)통수',
      percent: 12,
      amount: 115,
      spon: 0,
      dueDate: 21,
      isJjimed: false,
      isSponsored: false,
      jim_date: new Date(2020, 10, 28, 11, 1),
      img: '',
    },
    {
      id: 4,
      title: '[골라골라] 선빼고 다드려요! 2만원대 마우스',
      category: '가전',
      company: '(주)알지',
      percent: 30,
      amount: 40000,
      spon: 0,
      dueDate: 5,
      isJjimed: true,
      isSponsored: false,
      jim_date: new Date(2020, 11, 7, 11, 1),
      img: '',
    },
  ],
};

export default mockUserList;
